// This file is generated by media-elements/scripts/build-react!
export default React.ForwardRefExoticComponent<
  React.DetailedHTMLProps<React.VideoHTMLAttributes<HTMLVideoElement>, HTMLVideoElement>
>;
